version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.18.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            go test -coverprofile coverage.out
            go tool cover -html=coverage.out -o coverage.html
      - store_artifacts:
          path: coverage.html
workflows:
  test-workflow:
    jobs:
      - test
